import { Advisor, DynamicConfig, InductionStatus, ObjectionPlaybook, Tariff, TrainingResult } from "./types";

const inductionTitles = [
  "Se explicó proceso de cancelación correcta de movilidad",
  "Se explicó cuándo debe cancelar movilidad",
  "Se explicó a quién debe reportar incidencias de movilidad",
  "Se explicó procedimiento en caso de error o ausencia de movilidad",
  "Se explicó responsabilidad del asesor ante cambios o cancelaciones",
  "Se explicó proceso de comunicación con supervisor/coordinador",
  "Se explicó normativa básica de asistencia",
  "Se explicó uso correcto de herramientas asignadas",
  "Se explicó proceso de escalamiento de incidencias",
  "Se explicó protocolo de calidad comercial inicial",
];

const trainingModules = [
  "Introducción Vodafone",
  "Tarifas principales",
  "Retail y accesos",
  "Contrato y firma",
  "Calidad comercial",
  "Cancelación de movilidad",
  "Rebate y objeciones",
  "Cierre de venta",
  "Errores frecuentes",
  "Protocolo de incidencias",
];

const makeInduction = (completed: number) =>
  inductionTitles.map((title, index) => ({
    id: `ind-${index}`,
    title,
    status: (index < completed ? (index % 3 === 0 ? "reforzado" : "explicado") : index === completed ? "requiere nueva explicación" : "pendiente") as InductionStatus,
    explainedAt: index < completed ? "2026-06-10" : undefined,
    owner: index < completed ? "Laura Campos" : undefined,
    observation: index < completed ? "Explicación validada con ejemplo práctico." : "Pendiente de validar en sesión individual.",
    advisorConfirmation: index < completed,
    internalNote: index < completed ? `Constancia interna registrada para ${title.toLowerCase()}.` : "Sin evidencia registrada todavía.",
  }));

const makeTraining = (base: number) =>
  trainingModules.map((module, index) => ({
    module,
    checklist: ["Contenido visto", "Práctica completada", "Duda registrada"],
    examScore: Math.max(48, Math.min(98, base + index * 2 - 6)),
    practiceScore: Math.max(50, Math.min(100, base + index * 3 - 10)),
    progress: Math.max(20, Math.min(100, base + index * 4 - 18)),
    result: (base + index * 2 > 76 ? "apto" : base + index * 2 > 58 ? "necesita refuerzo" : "bloqueado") as TrainingResult,
  }));

export const advisorsSeed: Advisor[] = [
  {
    id: "adv-001",
    fullName: "Marina Soler Prieto",
    identifier: "INT-2401",
    entryDate: "2026-06-10",
    supervisor: "Laura Campos",
    shift: "Mañana",
    campaign: "Residencial fibra y móvil",
    status: "En formación",
    phone: "+34 600 111 222",
    email: "marina.soler@example.com",
    observations: "Buen dominio de argumentario, pendiente reforzar objeciones de precio.",
    tags: ["alto potencial", "tarifas"],
    progress: 72,
    nextAction: "Completar simulación de llamada y validar checklist de cancelación de movilidad.",
    access: {
      vodafoneUser: "activo",
      corporateAccess: "activo",
      learningPlatform: "activo",
      retail: "activo",
      contractDelivery: "confirmado",
      contractSignature: "firmado",
      requestDate: "2026-06-09T09:00:00Z",
      activationDate: "2026-06-10T11:20:00Z",
      owner: "Diego Ramos",
      notes: "Accesos validados sin incidencias.",
      incidents: [],
      internalEvidence: [{ id: "ev-1", date: "2026-06-10", type: "captura interna", description: "Validación de acceso y retail activo.", owner: "Diego Ramos" }],
    },
    induction: makeInduction(7),
    training: makeTraining(70),
    quality: [{ advisorId: "adv-001", date: "2026-06-11", callType: "simulada", greeting: true, offerExplanation: true, conditions: true, dataProcessing: true, correctClose: false, errors: ["Cierre poco directo"], score: 82, needsReinforcement: true, notes: "Mejorar cierre alternativo." }],
    changes: [{ date: "2026-06-11 09:30", author: "Laura Campos", action: "Actualización de avance", note: "Pasa a formación avanzada." }],
  },
  {
    id: "adv-002",
    fullName: "Nabil Ortega Ruiz",
    identifier: "INT-2402",
    entryDate: "2026-06-11",
    supervisor: "Sergio Vidal",
    shift: "Tarde",
    campaign: "Valor convergente",
    status: "Bloqueado",
    phone: "+34 600 333 444",
    email: "nabil.ortega@example.com",
    observations: "Bloqueo operativo por retail pendiente y ausencia de responsable asignado.",
    tags: ["bloqueo", "retail"],
    progress: 38,
    nextAction: "Asignar responsable y escalar activación de retail antes del cierre del día.",
    access: {
      vodafoneUser: "solicitado",
      corporateAccess: "activo",
      learningPlatform: "pendiente",
      retail: "pendiente",
      contractDelivery: "enviado",
      contractSignature: "pendiente",
      requestDate: "2026-06-09T08:00:00Z",
      notes: "Contrato enviado, sin firma. Retail supera umbral de 48 horas.",
      incidents: ["Retail pendiente más de 48 horas", "Falta responsable asignado"],
      internalEvidence: [{ id: "ev-2", date: "2026-06-11", type: "nota interna", description: "Se solicita prioridad de activación retail.", owner: "Sergio Vidal" }],
    },
    induction: makeInduction(3),
    training: makeTraining(48),
    quality: [{ advisorId: "adv-002", date: "2026-06-11", callType: "simulada", greeting: true, offerExplanation: false, conditions: false, dataProcessing: true, correctClose: false, errors: ["No explica permanencia", "No confirma condiciones"], score: 54, needsReinforcement: true, notes: "Requiere refuerzo urgente." }],
    changes: [{ date: "2026-06-11 16:00", author: "Sergio Vidal", action: "Incidencia creada", note: "Retail pendiente y contrato sin firma." }],
  },
  {
    id: "adv-003",
    fullName: "Claudia Beltrán Mesa",
    identifier: "INT-2403",
    entryDate: "2026-06-12",
    supervisor: "Laura Campos",
    shift: "Mañana",
    campaign: "Autónomos",
    status: "Credenciales pendientes",
    phone: "+34 600 555 666",
    email: "claudia.beltran@example.com",
    observations: "Documentación revisada. Pendiente activación de usuario Vodafone.",
    tags: ["pre-ingreso", "documentación ok"],
    progress: 51,
    nextAction: "Revisar credenciales al cumplir 24 horas y confirmar formación inicial.",
    access: {
      vodafoneUser: "solicitado",
      corporateAccess: "solicitado",
      learningPlatform: "activo",
      retail: "en proceso",
      contractDelivery: "confirmado",
      contractSignature: "firmado",
      requestDate: "2026-06-11T07:30:00Z",
      owner: "Marta León",
      notes: "Acceso en seguimiento dentro del SLA.",
      incidents: [],
      internalEvidence: [],
    },
    induction: makeInduction(5),
    training: makeTraining(61),
    quality: [],
    changes: [{ date: "2026-06-12 08:20", author: "Marta León", action: "Solicitud registrada", note: "Credenciales solicitadas sin datos sensibles." }],
  },
  {
    id: "adv-004",
    fullName: "Irene Vega Santos",
    identifier: "INT-2404",
    entryDate: "2026-06-09",
    supervisor: "Pablo Martín",
    shift: "Partido",
    campaign: "Low cost",
    status: "Listo para producción",
    phone: "+34 600 777 888",
    email: "irene.vega@example.com",
    observations: "Apta para primeras llamadas con seguimiento de calidad diario.",
    tags: ["producción inicial", "apta"],
    progress: 94,
    nextAction: "Iniciar producción inicial con revisión de primeras ventas.",
    access: {
      vodafoneUser: "activo",
      corporateAccess: "activo",
      learningPlatform: "activo",
      retail: "activo",
      contractDelivery: "confirmado",
      contractSignature: "firmado",
      requestDate: "2026-06-08T10:00:00Z",
      activationDate: "2026-06-09T12:10:00Z",
      owner: "Pablo Martín",
      notes: "Todas las validaciones cerradas.",
      incidents: [],
      internalEvidence: [{ id: "ev-4", date: "2026-06-09", type: "acta", description: "Constancia de inducción operativa completa.", owner: "Pablo Martín" }],
    },
    induction: makeInduction(10),
    training: makeTraining(88),
    quality: [{ advisorId: "adv-004", date: "2026-06-11", callType: "real", greeting: true, offerExplanation: true, conditions: true, dataProcessing: true, correctClose: true, errors: [], score: 94, needsReinforcement: false, notes: "Lista para seguimiento estándar." }],
    changes: [{ date: "2026-06-11 18:10", author: "Pablo Martín", action: "Validación final", note: "Apta para producción inicial." }],
  },
];

export const tariffsSeed: Tariff[] = [
  { id: "tar-1", name: "Fibra 600 + Móvil 50GB", price: 39.99, services: ["Fibra", "Móvil", "Fijo"], fiber: "600Mb", mobileLines: 1, gb: "50GB", streaming: "Opcional", commitment: "12 meses", conditions: "Instalación sujeta a cobertura. Precio promocional revisable según campaña.", commercialArgument: "Equilibrio sólido para hogares que quieren estabilidad y datos suficientes.", idealProfile: "Familias pequeñas o teletrabajo moderado.", frequentObjections: ["Está caro", "No quiero permanencia"], recommendedRebate: "Comparar coste total frente a contratar servicios separados y reforzar soporte de instalación.", status: "activa", segments: ["residencial", "valor", "fibra", "móvil"] },
  { id: "tar-2", name: "Solo Móvil Ilimitada", price: 24.99, services: ["Móvil"], fiber: "No aplica", mobileLines: 1, gb: "Ilimitados", commitment: "Sin permanencia móvil", conditions: "Uso razonable y cobertura móvil disponible.", commercialArgument: "Libertad para clientes que no quieren cambiar fibra y buscan muchos datos.", idealProfile: "Usuarios intensivos de móvil.", frequentObjections: ["Ya tengo otra compañía", "No quiero cambiar"], recommendedRebate: "Centrar la conversación en libertad, cobertura y simplicidad.", status: "activa", segments: ["móvil", "low cost", "residencial"] },
  { id: "tar-3", name: "Autónomo Pro Fibra 1Gb", price: 54.99, services: ["Fibra", "Móvil", "Soporte"], fiber: "1Gb", mobileLines: 2, gb: "100GB compartidos", commitment: "12 meses", conditions: "Requiere documentación de actividad profesional.", commercialArgument: "Productividad, estabilidad y soporte para negocio pequeño.", idealProfile: "Autónomos y microempresas.", frequentObjections: ["Lo voy a pensar", "No quiero dar mis datos"], recommendedRebate: "Diagnosticar coste de interrupciones y valor del soporte.", status: "activa", segments: ["autónomo", "empresa", "fibra", "valor"] },
];

export const objectionsSeed: ObjectionPlaybook[] = [
  ["Está caro", "residencial", "Entiendo el precio; revisemos valor total.", "Comprendo que el precio sea clave. Si comparamos fibra, datos, instalación y soporte, la tarifa busca reducir costes separados y darte estabilidad.", "¿Qué pagas ahora sumando fibra, líneas y extras?", "Cierre por comparación de valor", "No prometer descuentos no confirmados", "Cliente: Está caro. Asesor: Lo revisamos con números para confirmar si realmente mejora tu coste total."],
  ["Lo voy a pensar", "indeciso", "Perfecto, pensemos con criterios claros.", "Me parece responsable. Para ayudarte, dejemos definidos precio, permanencia, cobertura y fecha de instalación, así decides con información completa.", "¿Qué punto necesitas tener claro para decidir hoy?", "Cierre por siguiente paso concreto", "Presionar puede afectar calidad", "Cliente: Lo pienso. Asesor: Claro, ¿la duda principal es precio, cobertura o condiciones?"],
  ["No quiero permanencia", "sensibilidad contractual", "Revisemos qué permanencia aplica y por qué.", "Es una preocupación habitual. La permanencia suele estar vinculada a instalación o equipos; te explico alcance, duración y alternativas antes de avanzar.", "¿Tu rechazo viene por una mala experiencia anterior o por flexibilidad futura?", "Cierre por transparencia", "Ocultar permanencia es riesgo crítico", "Cliente: No quiero permanencia. Asesor: La condición se explica antes de decidir y vemos alternativas."],
  ["Tengo que hablarlo con mi pareja", "hogar compartido", "Tiene sentido decidirlo juntos.", "Claro, al ser un servicio del hogar conviene alinearlo. Te preparo un resumen simple con precio, ventajas y condiciones para que lo reviséis.", "¿Qué aspecto le preocupará más: precio, instalación o permanencia?", "Cierre con compromiso de revisión", "No invalidar al decisor ausente", "Cliente: Debo hablarlo. Asesor: Te ayudo con un resumen para resolver dudas concretas."],
  ["Ya tengo otra compañía", "competencia", "Perfecto, comparemos sin compromiso.", "Precisamente por eso la comparación debe ser objetiva: coste real, velocidad, datos, permanencia y servicio. Si no mejora, te lo diré claramente.", "¿Qué es lo mejor y lo peor de tu compañía actual?", "Cierre por contraste", "No desacreditar sin datos", "Cliente: Ya tengo compañía. Asesor: Comparemos lo que tienes frente a lo que necesitas."],
  ["No quiero cambiar", "resistencia", "Lo respeto; veamos si hay motivo real para cambiar.", "No se trata de cambiar por cambiar. Solo tiene sentido si ganas valor, ahorro o mejor servicio con condiciones claras.", "¿Qué tendría que mejorar para que consideraras una alternativa?", "Cierre por beneficio mínimo", "Evitar insistencia repetitiva", "Cliente: No quiero cambiar. Asesor: Entonces confirmemos si existe una mejora real para ti."],
  ["He tenido mala experiencia", "riesgo reputacional", "Gracias por contarlo; revisemos qué pasó.", "Entiendo que una mala experiencia pesa. Para no repetirla, primero identifico el problema anterior y te explico cómo se gestionaría ahora.", "¿La experiencia fue por instalación, factura, cobertura o atención?", "Cierre por reparación de confianza", "Minimizar la experiencia del cliente", "Cliente: Tuve mala experiencia. Asesor: Quiero entenderla antes de proponerte nada."],
  ["No me interesa", "rechazo rápido", "De acuerdo, solo confirmo si encaja.", "Lo respeto. Antes de cerrar, dime si actualmente buscas ahorrar, mejorar datos o evitar cortes; si no hay encaje, no avanzamos.", "¿Hay algún punto de tu servicio actual que sí mejorarías?", "Cierre por permiso", "Insistir sin diagnóstico", "Cliente: No me interesa. Asesor: Perfecto, ¿hay algo de tu servicio actual que cambiarías?"],
  ["Llámame otro día", "postergación", "Claro, agendemos con motivo concreto.", "Sin problema. Para que la próxima llamada sea útil, dejamos anotada la duda principal y una hora concreta.", "¿Qué día y franja te viene bien para revisar precio y condiciones?", "Cierre por agenda", "Llamar sin consentimiento claro", "Cliente: Otro día. Asesor: Lo agendo y dejamos claro qué revisaremos."],
  ["No quiero dar mis datos", "privacidad", "Es correcto proteger tus datos.", "Haces bien en ser prudente. Solo se solicitan datos necesarios en el momento adecuado, explicando finalidad y tratamiento antes de continuar.", "¿Qué dato te preocupa compartir y por qué?", "Cierre por seguridad y transparencia", "Pedir datos antes de explicar finalidad", "Cliente: No doy datos. Asesor: Te explico finalidad y tú decides si avanzar."],
  ["No confío en ofertas por teléfono", "confianza", "Es normal querer garantías.", "Lo entiendo. Por eso debemos explicar condiciones, confirmar identidad del proceso y dejar constancia clara antes de cualquier decisión.", "¿Qué necesitarías para sentirte seguro revisando la oferta?", "Cierre por validación de confianza", "Promesas vagas o urgencia artificial", "Cliente: No confío. Asesor: Validamos condiciones paso a paso y sin presión."],
].map(([objection, customerType, shortAnswer, professionalAnswer, diagnosticQuestion, closingTechnique, qualityRisk, callExample], index) => ({
  id: `obj-${index + 1}`,
  objection,
  customerType,
  shortAnswer,
  professionalAnswer,
  diagnosticQuestion,
  closingTechnique,
  qualityRisk,
  callExample,
}));

export const dynamicConfigSeed: DynamicConfig = {
  customFields: ["Canal de incorporación", "Nivel de experiencia", "Disponibilidad extra"],
  customStatuses: ["Validación documental", "Producción acompañada"],
  trainingModules,
  objectionTypes: objectionsSeed.map((item) => item.objection),
  tariffFamilies: ["residencial", "autónomo", "empresa", "low cost", "valor", "fibra", "móvil", "streaming"],
  checklistTemplates: inductionTitles,
  incidentTypes: ["Retail pendiente", "Credencial bloqueada", "Contrato sin firma", "Formación incompleta", "Calidad crítica"],
  enabledModules: ["Dashboard", "Asesores", "Accesos", "Inducción", "Tarifas", "Rebate", "Formación", "Calidad", "Reportes", "Modo TV", "Configuración"],
  aiBaseTexts: ["Responder en tono profesional y accionable", "No solicitar ni registrar contraseñas", "Priorizar bloqueos por impacto operativo"],
};
